version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.21
    - 14.14.25
    - 14.14.26
    - 14.14.27
    - 14.14.28
    - 14.14.29
    - 14.14.31
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: node
    versions:
    - 15.10.0
    - 15.12.0
    - 15.14.0
    - 15.7.0
    - 15.8.0
    - 16.0.0
  - dependency-name: npm
    versions:
    - 7.10.0
    - 7.11.0
    - 7.5.2
    - 7.5.3
    - 7.5.4
    - 7.5.6
    - 7.6.0
    - 7.6.1
    - 7.6.2
    - 7.6.3
    - 7.7.0
    - 7.7.3
    - 7.7.4
    - 7.7.5
    - 7.7.6
    - 7.8.0
    - 7.9.0
  - dependency-name: ethers
    versions:
    - 5.0.27
    - 5.0.28
    - 5.0.29
    - 5.0.30
    - 5.0.31
    - 5.0.32
    - 5.1.0
    - 5.1.2
    - 5.1.3
  - dependency-name: chalk
    versions:
    - 4.1.1
  - dependency-name: escape-string-regexp
    versions:
    - 5.0.0
  - dependency-name: solc
    versions:
    - 0.8.2
    - 0.8.3
    - 0.8.4
  - dependency-name: truffle
    versions:
    - 5.1.64
    - 5.1.65
    - 5.1.66
    - 5.1.67
    - 5.2.1
    - 5.2.2
    - 5.2.3
    - 5.2.4
    - 5.2.5
    - 5.2.6
    - 5.3.0
    - 5.3.1
    - 5.3.2
  - dependency-name: js-yaml
    versions:
    - 4.0.0
    - 4.1.0
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
    - 8.1.0
    - 8.2.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
    - 4.22.0
  - dependency-name: ajv
    versions:
    - 7.0.4
    - 7.1.0
    - 7.1.1
    - 7.2.1
    - 7.2.3
    - 7.2.4
    - 8.0.1
    - 8.0.2
    - 8.0.3
    - 8.0.5
    - 8.1.0
  - dependency-name: typescript
    versions:
    - 4.1.5
    - 4.2.2
    - 4.2.3
    - 4.2.4
  - dependency-name: web3
    versions:
    - 1.3.4
    - 1.3.5
  - dependency-name: node-gyp
    versions:
    - 7.1.2
    - 8.0.0
  - dependency-name: ethereumjs-util
    versions:
    - 7.0.10
    - 7.0.8
    - 7.0.9
  - dependency-name: glob
    versions:
    - 7.1.6
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 6.0.0
  - dependency-name: "@ensdomains/ens"
    versions:
    - 0.6.0
  - dependency-name: openzeppelin-solidity
    versions:
    - 3.4.0
    - 3.4.1
    - 4.0.0
  - dependency-name: "@types/mocha"
    versions:
    - 8.2.1
    - 8.2.2
  - dependency-name: snarkjs
    versions:
    - 0.3.59
    - 0.3.60
  - dependency-name: truffle-plugin-verify
    versions:
    - 0.5.5
    - 0.5.6
    - 0.5.7
  - dependency-name: npm-watch
    versions:
    - 0.9.0
  - dependency-name: "@eth-optimism/plugins"
    versions:
    - 0.0.20
  - dependency-name: chai
    versions:
    - 4.3.0
    - 4.3.1
    - 4.3.3
    - 4.3.4
  - dependency-name: lerna
    versions:
    - 4.0.0
  - dependency-name: events
    versions:
    - 3.3.0
  - dependency-name: bn.js
    versions:
    - 5.2.0
  - dependency-name: lodash
    versions:
    - 4.17.20
    - 4.17.21
  - dependency-name: es6-promisify
    versions:
    - 6.1.1
  - dependency-name: braces
    versions:
    - 3.0.2
  - dependency-name: bluebird
    versions:
    - 3.7.2
  - dependency-name: rimraf
    versions:
    - 3.0.2
  - dependency-name: eth-sig-util
    versions:
    - 3.0.1
