FROM mhart/alpine-node:8

RUN apk add --no-cache git curl make gcc g++ python linux-headers

RUN npm install -g truffle@4.1.13 typescript@2.7.1

ADD package.json package.json

ADD package-lock.json package-lock.json

RUN npm install

RUN apk del git curl make gcc g++ linux-headers

ADD . .

RUN npm run compile

CMD npm run testdocker
