version: '3'
services:
  ganache:
    build:
      context: .
      dockerfile: Dockerfile.ganachecli
    expose:
      - "8545"
    ports:
      - "8545:8545"
    logging:
      driver: none

  test:
    depends_on:
      - ganache
    build:
      context: .
      dockerfile: Dockerfile.test
